package com.cidic.equipment.model;
// default package
// Generated 2017-4-17 10:51:18 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Color generated by hbm2java
 */
@Entity
@Table(name = "color", catalog = "equipment")
@JsonIgnoreProperties(value={"hibernateLazyInitializer","handler","operations","vehicleColors"})
public class Color implements java.io.Serializable {

	private Integer id;
	private String name;
	private String colorValue;
	private Date createTime;
	private Set<VehicleColor> vehicleColors = new HashSet<VehicleColor>(0);

	public Color() {
	}

	public Color(String name, String colorValue, Date createTime) {
		this.name = name;
		this.colorValue = colorValue;
		this.createTime = createTime;
	}

	public Color(String name, String colorValue, Date createTime, Set<VehicleColor> vehicleColors) {
		this.name = name;
		this.colorValue = colorValue;
		this.createTime = createTime;
		this.vehicleColors = vehicleColors;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "color_value", nullable = false, length = 15)
	public String getColorValue() {
		return this.colorValue;
	}

	public void setColorValue(String colorValue) {
		this.colorValue = colorValue;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "color")
	@LazyCollection(LazyCollectionOption.EXTRA)
	public Set<VehicleColor> getVehicleColors() {
		return this.vehicleColors;
	}

	public void setVehicleColors(Set<VehicleColor> vehicleColors) {
		this.vehicleColors = vehicleColors;
	}

}
