package com.cidic.equipment.model;
// default package
// Generated 2017-4-14 17:05:01 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VehicleColor generated by hbm2java
 */
@Entity
@Table(name = "vehicle_color", catalog = "equipment")
public class VehicleColor implements java.io.Serializable {

	private Integer id;
	private VehicleInfo vehicleInfo;
	private int colorId;

	public VehicleColor() {
	}

	public VehicleColor(VehicleInfo vehicleInfo, int colorId) {
		this.vehicleInfo = vehicleInfo;
		this.colorId = colorId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "vehicleId", nullable = false)
	public VehicleInfo getVehicleInfo() {
		return this.vehicleInfo;
	}

	public void setVehicleInfo(VehicleInfo vehicleInfo) {
		this.vehicleInfo = vehicleInfo;
	}

	@Column(name = "colorId", nullable = false)
	public int getColorId() {
		return this.colorId;
	}

	public void setColorId(int colorId) {
		this.colorId = colorId;
	}

}
