package com.cidic.equipment.model;
// default package
// Generated 2017-4-17 10:51:18 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * VehicleColor generated by hbm2java
 */
@Entity
@Table(name = "vehicle_color", catalog = "equipment")
public class VehicleColor implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private Color color;
	private VehicleInfo vehicleInfo;

	public VehicleColor() {
	}

	public VehicleColor(Color color, VehicleInfo vehicleInfo) {
		this.color = color;
		this.vehicleInfo = vehicleInfo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "colorId", nullable = false)
	public Color getColor() {
		return this.color;
	}

	public void setColor(Color color) {
		this.color = color;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "vehicleId", nullable = false)
	@JsonIgnore
	public VehicleInfo getVehicleInfo() {
		return this.vehicleInfo;
	}

	public void setVehicleInfo(VehicleInfo vehicleInfo) {
		this.vehicleInfo = vehicleInfo;
	}

}
