package com.cidic.equipment.model;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * VehicleInfo generated by hbm2java
 */
@Entity
@Table(name = "vehicle_info", catalog = "equipment")
public class VehicleInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private int categoryId;
	private int brandId;
	private byte entry;
	private String imageUrl1;
	private String imageUrl2;
	private String style;
	private String modelUrl;
	private Set<VehicleColor> vehicleColors = new HashSet<VehicleColor>(0);
	private Set<ComponentInfo> componentInfos = new HashSet<ComponentInfo>(0);

	public VehicleInfo() {
	}

	public VehicleInfo(int categoryId, byte entry, String style, String modelUrl) {
		this.categoryId = categoryId;
		this.entry = entry;
		this.style = style;
		this.modelUrl = modelUrl;
	}

	public VehicleInfo(int categoryId, byte entry, String imageUrl1, String imageUrl2, String style, String modelUrl,
			Set<VehicleColor> vehicleColors, Set<ComponentInfo> componentInfos) {
		this.categoryId = categoryId;
		this.entry = entry;
		this.imageUrl1 = imageUrl1;
		this.imageUrl2 = imageUrl2;
		this.style = style;
		this.modelUrl = modelUrl;
		this.vehicleColors = vehicleColors;
		this.componentInfos = componentInfos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "categoryId", nullable = false)
	public int getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(int categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "brandId", nullable = false)
	public int getBrandId() {
		return brandId;
	}

	public void setBrandId(int brandId) {
		this.brandId = brandId;
	}

	@Column(name = "entry", nullable = false)
	public byte getEntry() {
		return this.entry;
	}

	public void setEntry(byte entry) {
		this.entry = entry;
	}

	@Column(name = "imageUrl1")
	public String getImageUrl1() {
		return this.imageUrl1;
	}

	public void setImageUrl1(String imageUrl1) {
		this.imageUrl1 = imageUrl1;
	}

	@Column(name = "imageUrl2")
	public String getImageUrl2() {
		return this.imageUrl2;
	}

	public void setImageUrl2(String imageUrl2) {
		this.imageUrl2 = imageUrl2;
	}

	@Column(name = "style", nullable = false)
	public String getStyle() {
		return this.style;
	}

	public void setStyle(String style) {
		this.style = style;
	}

	@Column(name = "modelUrl", nullable = false)
	public String getModelUrl() {
		return this.modelUrl;
	}

	public void setModelUrl(String modelUrl) {
		this.modelUrl = modelUrl;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vehicleInfo")
	public Set<VehicleColor> getVehicleColors() {
		return this.vehicleColors;
	}

	public void setVehicleColors(Set<VehicleColor> vehicleColors) {
		this.vehicleColors = vehicleColors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vehicleInfo")
	public Set<ComponentInfo> getComponentInfos() {
		return this.componentInfos;
	}

	public void setComponentInfos(Set<ComponentInfo> componentInfos) {
		this.componentInfos = componentInfos;
	}

}
