package com.cidic.equipment.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VehicleInfo generated by hbm2java
 */
@Entity
@Table(name = "vehicle_info", catalog = "equipment")
public class VehicleInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private int categoryId;
	private int brandId;
	private byte entry;
	private String imageUrl1;
	private String imageUrl2;
	private String style;
	private String modelUrl;
	private Date createTime;
	private String componentInfos; //部件信息
	private Date onSaleDate;
	
	private Set<VehicleColor> vehicleColors = new HashSet<VehicleColor>(0);
	private Set<VehicleTexture> vehicleTextures = new HashSet<VehicleTexture>(0);
	
	public VehicleInfo() {
	}

	public VehicleInfo(int categoryId, byte entry, String style, String modelUrl) {
		this.categoryId = categoryId;
		this.entry = entry;
		this.style = style;
		this.modelUrl = modelUrl;
	}

	public VehicleInfo(int categoryId, byte entry, String imageUrl1, String imageUrl2, String style, String modelUrl,
			Set<VehicleColor> vehicleColors) {
		this.categoryId = categoryId;
		this.entry = entry;
		this.imageUrl1 = imageUrl1;
		this.imageUrl2 = imageUrl2;
		this.style = style;
		this.modelUrl = modelUrl;
		this.vehicleColors = vehicleColors;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "categoryId", nullable = false)
	public int getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(int categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "brandId", nullable = false)
	public int getBrandId() {
		return brandId;
	}

	public void setBrandId(int brandId) {
		this.brandId = brandId;
	}

	@Column(name = "entry", nullable = false)
	public byte getEntry() {
		return this.entry;
	}

	public void setEntry(byte entry) {
		this.entry = entry;
	}

	@Column(name = "imageUrl1")
	public String getImageUrl1() {
		return this.imageUrl1;
	}

	public void setImageUrl1(String imageUrl1) {
		this.imageUrl1 = imageUrl1;
	}

	@Column(name = "imageUrl2")
	public String getImageUrl2() {
		return this.imageUrl2;
	}

	public void setImageUrl2(String imageUrl2) {
		this.imageUrl2 = imageUrl2;
	}

	@Column(name = "style", nullable = false)
	public String getStyle() {
		return this.style;
	}

	public void setStyle(String style) {
		this.style = style;
	}

	@Column(name = "modelUrl", nullable = false)
	public String getModelUrl() {
		return this.modelUrl;
	}

	public void setModelUrl(String modelUrl) {
		this.modelUrl = modelUrl;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vehicleInfo")
	public Set<VehicleColor> getVehicleColors() {
		return this.vehicleColors;
	}

	public void setVehicleColors(Set<VehicleColor> vehicleColors) {
		this.vehicleColors = vehicleColors;
	}

	@Column(name = "component_info", nullable = false, length = 65535)
	public String getComponentInfos() {
		return componentInfos;
	}

	public void setComponentInfos(String componentInfos) {
		this.componentInfos = componentInfos;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vehicleInfo")
	public Set<VehicleTexture> getVehicleTextures() {
		return vehicleTextures;
	}
	
	public void setVehicleTextures(Set<VehicleTexture> vehicleTextures) {
		this.vehicleTextures = vehicleTextures;
	}


	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", nullable = false, length = 19)
	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "on_sale_date", nullable = false, length = 19)
	public Date getOnSaleDate() {
		return onSaleDate;
	}

	
	public void setOnSaleDate(Date onSaleDate) {
		this.onSaleDate = onSaleDate;
	}

	
}
