package com.cidic.equipment.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * VehicleTexture generated by hbm2java
 */
@Entity
@Table(name = "vehicle_texture", catalog = "equipment")
public class VehicleTexture implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private int vehicleId;
	private int textureId;

	public VehicleTexture() {
	}

	public VehicleTexture(int vehicleId, int textureId) {
		this.vehicleId = vehicleId;
		this.textureId = textureId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "vehicleId", nullable = false)
	public int getVehicleId() {
		return this.vehicleId;
	}

	public void setVehicleId(int vehicleId) {
		this.vehicleId = vehicleId;
	}

	@Column(name = "textureId", nullable = false)
	public int getTextureId() {
		return this.textureId;
	}

	public void setTextureId(int textureId) {
		this.textureId = textureId;
	}

}
